// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order-history-event.proto

package com.consumer.example.proto;

public final class OrderHistoryEventWrapper {
  private OrderHistoryEventWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_consumer_OrderHistoryEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_consumer_OrderHistoryEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031order-history-event.proto\022\010consumer\"t\n" +
      "\021OrderHistoryEvent\022\017\n\007orderId\030\001 \001(\t\022\021\n\to" +
      "rderName\030\002 \001(\t\022\022\n\ncustomerId\030\003 \001(\t\022\024\n\014or" +
      "der_status\030\004 \001(\t\022\021\n\toperation\030\005 \001(\tB8\n\032c" +
      "om.consumer.example.protoB\030OrderHistoryE" +
      "ventWrapperP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_consumer_OrderHistoryEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_consumer_OrderHistoryEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_consumer_OrderHistoryEvent_descriptor,
        new java.lang.String[] { "OrderId", "OrderName", "CustomerId", "OrderStatus", "Operation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
