// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order-history-event.proto

package com.consumer.example.proto;

public interface OrderHistoryEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:consumer.OrderHistoryEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderId = 1;</code>
   * @return The orderId.
   */
  java.lang.String getOrderId();
  /**
   * <code>string orderId = 1;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>string orderName = 2;</code>
   * @return The orderName.
   */
  java.lang.String getOrderName();
  /**
   * <code>string orderName = 2;</code>
   * @return The bytes for orderName.
   */
  com.google.protobuf.ByteString
      getOrderNameBytes();

  /**
   * <code>string customerId = 3;</code>
   * @return The customerId.
   */
  java.lang.String getCustomerId();
  /**
   * <code>string customerId = 3;</code>
   * @return The bytes for customerId.
   */
  com.google.protobuf.ByteString
      getCustomerIdBytes();

  /**
   * <code>string order_status = 4;</code>
   * @return The orderStatus.
   */
  java.lang.String getOrderStatus();
  /**
   * <code>string order_status = 4;</code>
   * @return The bytes for orderStatus.
   */
  com.google.protobuf.ByteString
      getOrderStatusBytes();

  /**
   * <code>string operation = 5;</code>
   * @return The operation.
   */
  java.lang.String getOperation();
  /**
   * <code>string operation = 5;</code>
   * @return The bytes for operation.
   */
  com.google.protobuf.ByteString
      getOperationBytes();
}
